### ISSUE TITLE
Casual TODO list

### ISSUE THREAD

**Issue by wwylele** [wwylele/mhrice#15]
I'll put whatever small items to do that I come up with here....

**Comment by wwylele** [comment]
- [x] Long list sorting
 - [x] buddy gears
 - [x] rampage data
 - [x] map
 - [x] NPC request

**Comment by wwylele** [comment]
- [x] memorize language selection
   - cookie stuff

**Comment by wwylele** [comment]
- [x] search bar

**Comment by wwylele** [comment]
- [x] `<!DOCTYPE html>`

**Comment by wwylele** [comment]
- [x] ramp up skill detail

**Comment by wwylele** [comment]
- [x] skill and ramp up skill related gears
 - [x] item usage on deco and ramp up skill

**Comment by wwylele** [comment]
- [x] 404 page

**Comment by wwylele** [comment]
- [x] armor ~~/ weapon / deco~~ crafting cost
   - Where is this?

**Comment by wwylele** [comment]
- [x] decode msg linebreak into html
   - Also look into space rendering. Check out css `white-space` property
   - One option is to use the `<pre>` tag. The other is to convert linebreak into explicit `<br/>` + potentially a marker
   - double check the copy-paste behavior

**Comment by wwylele** [comment]
- [x] preprocess monster data. There shouldn't be any failure during html generation stage
 - [x] part diagram chroma key

**Comment by wwylele** [comment]
- [x] quest monster list: hide non-target
- [x] Mark afflicted monster

**Comment by wwylele** [comment]
- [x] Mark MR quest with NPC
 - [x] Fix afflicted material color

**Comment by wwylele** [comment]
- [x] armor upgrade list

**Comment by wwylele** [comment]
- [x] afflicted material reward from monster

**Comment by wwylele** [comment]
- [x] monster hitzone phase name (manually from TDB)

**Comment by wwylele** [comment]
- [x] Show more information about progress to unlock certain things (armor, weapon, deco, etc.)

**Comment by wwylele** [comment]
- [x] more stuff on the map: spiribirds, other creatures, monster spawning point etc

**Comment by wwylele** [comment]
- [x] special item source (e.g. Sinister Gloomcloth)

**Comment by wwylele** [comment]
- [x] v11 afflicted rewards
- [x] v11 afflicted investigation

**Comment by wwylele** [comment]
- [x] side bar menu

**Comment by wwylele** [comment]
- [ ] afflicted investigation multiplayer factor

**Comment by wwylele** [comment]
- [ ] more info (monster spawning etc) in map

**Comment by wwylele** [comment]
Misc stuff
 - [x] offcuts item convert table 
 - [x] shops
 - [ ] Bahari lottery
 - [ ] investigation lottery
 - [x] BBQ data
 - [x] Alchemy data
 - [x]  combine item

**Comment by wwylele** [comment]
- [x] Arena data

**Comment by wwylele** [comment]
- [x] add mark on weapons in the tree that can be layered
 - [x] general improvement on weapon tree

**Comment by wwylele** [comment]
- [x] HP fluctuation

**Comment by wwylele** [comment]
- [x] Page title improvement, multi language

**Comment by wwylele** [comment]
- [x] quest unlock progress, and auto clearing.

**Comment by wwylele** [comment]
- [x] armor male/female flag

**Comment by wwylele** [comment]
- [x] chaotic weapon special stat

**Comment by wwylele** [comment]
- [x] arena additional reward
 - [x]  where is the count for quest bonus reward?

**Comment by wwylele** [comment]
- [x] item mix source/dest

**Comment by wwylele** [comment]
- [x] DLC
- [ ] data\Define\Lobby\Facility\Village_MR\CommercialStuffUserData

**Comment by wwylele** [comment]
- [x] kinsect

**Comment by wwylele** [comment]
- [x] monster user_data: block_move_data.user
 - [x] monster user_data: pop_parameter_data.user
 - [x] stamina_data.user

**Comment by wwylele** [comment]
- [x] monster unique mystery data

**Comment by wwylele** [comment]
- [x] award
 - [x] achievement

**Comment by wwylele** [comment]
- [ ] change marker on version list for each page

**Comment by wwylele** [comment]
- [ ] use_die_damage_data

**Comment by wwylele** [comment]
- [ ] system_enemy_map_setting_data.user
