### ISSUE TITLE
Update checklist

### ISSUE THREAD

**Issue by wwylele** [wwylele/mhrice#20]
- [x] Verify whether PAK has new format
 - [x] Verify whether TDB has new format
 - [x] Run all known format scan
 - [x] Update suffix version numbers
 - [x] Dump tree
 - [x] Verify RSZ formats against new TDB
 - [x] Dump new json
